### ISSUE TITLE
Check for HA restart: Home Assistant Rest API returned 404: Not found

### ISSUE THREAD

**Issue by ezspot** [runelangseid/hassio-futurehome2mqtt#2]
Using new hub(Zigbee and Z-wave supoport) with version latest firmware and software.
Home assistant is running on a Pie 4.

Nothing appears in the Gui of Home Assistant. Any tips?

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Futurehome FIMP to MQTT
Starting service...
Connection to 192.168.1.57
User:  mqttuser
Port:  1884
Client id:  fimptoha
Home Assistant long-lived access token:  **...
Home Assistant host:  None
Debug :  False
Selected devices 
MQTT client: Connected successfull
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Asking FIMP to expose all devices...
Received list of devices from FIMP. FIMP reported 36 devices
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Devices without rooms are ignored
Creating: 8 lampe
- Functionality: lighting
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/app/pyfimptoha/client.py", line 133, in on_message
    self.create_components(data["val"]["param"]["device"])
  File "/app/pyfimptoha/client.py", line 275, in create_components
    light = Light(service_name, service, device)
  File "/app/pyfimptoha/light.py", line 49, in __init__
    self._brightness_value = self._device["param"]["dimValue"]
KeyError: 'dimValue'
Publishing init states
- lights
- switches
- sensors
Sleeping forever...

**Comment by Jhonatan89lutt** [comment]
> Bruker ny hub (Zigbee og Z-wave support) med siste versjon av fastvare og programvare. Hjemmeassistent kjører på en Pie 4.
> 
> Ingenting vises i Gui of Home Assistant. Noen tips?
> 
> [s6-init] gjør brukerleverte filer tilgjengelige på /var/run/s6/etc...exited 0. [s6-init] sikre at brukerleverte filer har riktige perms... exited 0. [fix-attrs.d] bruker rettelser for eierskap og tillatelser ... [fix-attrs.d] ferdig. [cont-init.d] utfører beholderinitialiseringsskript... [cont-init.d] ferdig. [services.d] starter tjenester [services.d] ferdig. Starter Futurehome FIMP til MQTT Starter tjenesten... Tilkobling til 192.168.1.57 Bruker: mqttuser Port: 1884 Klient-ID: fimptoha Hjemmeassistent langvarig tilgangstoken: **... Hjemmeassistent - vert: Ingen Feilsøking : Falsk Valgte enheter MQTT-klient: Tilkoblet vellykket Se etter HA-omstart: Home Assistant Rest API returnerte 404: Ikke funnet. Sensor `ha_uptime_minutes`ble ikke funnet. Ble sensor `HA uptime moment`lagt til som nevnt i README? check_restarts: Kunne ikke hente oppetid fra HA. Prøver igjen om 60 sekunder Ber FIMP om å avsløre alle enheter... Mottatt liste over enheter fra FIMP. FIMP rapporterte 36 enheter Unntak i tråd Thread-1: Traceback (siste anrop sist): Fil "/usr/lib/python3.9/threading.py", linje 954, i _bootstrap_inner Enheter uten rom ignoreres Oppretting: 8 lampe
> 
> * Funksjonalitet: lighting 
>   self.run() 
>   Fil "/usr/lib/python3.9/threading.py", linje 892, i run 
>   self._target(*self._args, **self._kwargs) 
>   Fil "/usr/lib /python3.9/site-packages/paho/mqtt/client.py", linje 3452, i _thread_main 
>   self.loop_forever(retry_first_connection=True) 
>   fil "/usr/lib/python3.9/site-packages/paho/mqtt/ client.py", linje 1779, i loop_forever 
>   rc = self.loop(timeout, max_packets) 
>   Fil "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", linje 1181, i loop 
>   rc = self.loop_read(max_packets) 
>   Fil "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", linje 1572, i loop_read 
>   rc = self._packet_read()
>   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
>   rc = self._packet_handle()
>   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
>   return self._handle_publish()
>   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
>   self._handle_on_message(message)
>   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
>   self.on_message(self, self._userdata, message)
>   File "/app/pyfimptoha/client.py", line 133, in on_message
>   self.create_components(data["val"]["param"]["device"])
>   File "/app/pyfimptoha/client.py", line 275, in create_components
>   light = Light(tjeneste_navn, tjeneste, enhet) 
>   Fil "/app/pyfimptoha/light.py", linje 49, i **init** 
>   self._brightness_value = self._device["param"]["dimValue"] 
>   KeyError: 'dimValue' 
>   Publisering init opplyser
> * lys
> * brytere
> * sensorer 
>   Sover for alltid...


Jeg får heller ingen lys opp i Dashboard å får meldingen Som du viser til over. Noen som kan svare på hva som gjør dette? 
her er deler av min melding : Skipping: 119 Røyldetektor Lucas
Skipping: 4 Trapp Led
Skipping: 124 Brannalarm 4 hovedsoverom
Skipping: 125 Brannalarm 8 Vaskerom oppe
Skipping: 126 Brannalarm 7 Jannicke
Skipping: 127 Hovedsoverom Ragnhild -  Lars nydimmer
Skipping: 128 Hovedsoverom Bryter
Skipping: 136 StueBryter 
Skipping: 137 Hovedsoverom Bryter 2 dør
Publishing init states
- lights
- switches
- sensors
Sleeping forever...
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds
Check for HA restart: Home Assistant Rest API returned 404: Not found. Sensor `ha_uptime_minutes` was not found. Was sensor `HA uptime moment` added as mentioned in the README?
check_restarts: Could not get uptime from HA. Trying again in 60 seconds

**Comment by runelangseid** [comment]
As of version 0.2 the restart sensor is no longer needed as Home Assistant is announcing reboots on MQTT. This should resolve this issue
