### ISSUE TITLE
Light example wo plugin?

### ISSUE THREAD

**Issue by kristianolofsson** [runelangseid/hassio-futurehome2mqtt#3]
Cant get the mqtt light to work. Can you please provide example with the new state_value_template

The following gives an "unknown" state
`light:
  - platform: mqtt
    name: "Storage Roof"
    state_topic:   "pt:j1/mt:evt/rt:dev/rn:zw/ad:1/sv:out_lvl_switch/ad:6_0"
    command_topic: "pt:j1/mt:cmd/rt:dev/rn:zw/ad:1/sv:out_lvl_switch/ad:6_0"
    payload_on:  '{"props":{},"serv":"out_lvl_switch","tags":[],"type":"cmd.binary.set","uid" : "b1045ae0-d2bc-11ec-901b-194ce6613fff","val":true,"val_t":"bool"}'
    payload_off: '{"props":{},"serv":"out_lvl_switch","tags":[],"type":"cmd.binary.set","uid" : "b1045ae0-d2bc-11ec-901b-194ce6613fff","val":false,"val_t":"bool"}'
    state_value_template: '{{ value_json.val }}'
    state_on: true
    state_off: false

**Comment by runelangseid** [comment]
See how lights are handled in version 0.2: https://github.com/runelangseid/hassio-futurehome2mqtt/blob/master/futurehome2mqtt/pyfimptoha/light.py#L30. Can be used with out this plugin.
